### ISSUE TITLE
没有连接ssh的选项

### ISSUE THREAD

**Issue by xiahuan710** [QQxiaoming/quardCRT#15]
没有连接ssh的选项，我觉得要有限做ssh的会比较有市场

**Comment by QQxiaoming** [comment]
感谢您的意见，目前主分支已经初步实现了ssh2的支持，暂时还没有release版本，预计会在V0.3.x版本集成。https://github.com/QQxiaoming/quardCRT/blob/1dd9c98084c7b5a81c2e84735c50963717ebf76d/CHANGELOG.md?plain=1#L1-L13

**Comment by QQxiaoming** [comment]
V0.3.0版本已发布，功能已集成。[V0.3.0](https://github.com/QQxiaoming/quardCRT/releases/tag/V0.3.0)
