### ISSUE TITLE
compile error under linux!

### ISSUE THREAD

**Issue by zhangfq-chemistry** [QQxiaoming/quardCRT#21]
make: *** No rule to make target 'lang/quardCRT_ko_KR.qm', needed by 'build_release/rcc/qrc_resource.cpp'.  Stop.

**Comment by QQxiaoming** [comment]
Hello @zhangfq-chemistry, you need to execute the command `lrelease ./quardCRT.pro` to create a localized translation file before compiling.

If you use qt creator, you can also choose Tools--External--Linguist--lrelease. 

This will solve your problem easily.
​

**Comment by zhangfq-chemistry** [comment]
Thanks a lot!
