### ISSUE TITLE
compile under win10/qt6.6.1

### ISSUE THREAD

**Issue by zhangfq-chemistry** [QQxiaoming/quardCRT#22]
In file included from lib\ptyqt\ptyqt.cpp:5:
lib\ptyqt\winptyprocess.h:5:10: fatal error: winpty.h: No such file or directory
    5 | #include "winpty.h"
      |          ^~~~~~~~~~
compilation terminated.
mingw32-make[1]: *** [Makefile.Release:27008: build_release/obj/ptyqt.o] Error 1
mingw32-make[1]: Leaving directory 'D:/zhangfq/quardCRT'
mingw32-make: *** [Makefile:45: release] Error 2

**Comment by QQxiaoming** [comment]
Currently this project has some upstream dependencies on libs, I put their source code in the depend directory, which need to be compiled into static or dynamic libraries for the project to use, this [document](https://github.com/QQxiaoming/quardCRT/blob/main/DEVELOPNOTE.md) has a detailed description, but it is only in Chinese.

**Comment by zhangfq-chemistry** [comment]
我使用mingw32-make编译的。win10必须装mingw64吗？我看到脚本里用这个。使用Qt6.6.1自带的编译器可以吗？谢谢您！

**Comment by QQxiaoming** [comment]
> 我使用mingw32-make编译的。win10必须装mingw64吗？我看到脚本里用这个。使用Qt6.6.1自带的编译器可以吗？谢谢您！

应当是可以的，但我没有完全确认，另外也可以直接下载winpty预编译二进制的lib库，它们完全可以被Qt6.6.1自带的mingw工具链链接，这点我确认过。下载链接：https://github.com/rprichard/winpty/releases

**Comment by zhangfq-chemistry** [comment]
多谢作者！我试试。
