### ISSUE TITLE
Would you like to tell me again how to dispose the following error? Thanks!

### ISSUE THREAD

**Issue by zhangfq-chemistry** [QQxiaoming/quardCRT#30]
make: *** No rule to make target 'lang/quardCRT_ko_KR.qm', needed by 'build_release/rcc/qrc_resource.cpp'.  Stop.

**Comment by QQxiaoming** [comment]
Please refer here https://github.com/QQxiaoming/quardCRT/issues/21#issuecomment-1887340951
